### ISSUE TITLE
can't login to the app even after change the clientID

### ISSUE THREAD

**Issue by arief-prasetyo** [subhendukundu/Electron-GoogleSheet#1]
Good Night,
i have a problem to login to the app even after I've changed the clientID data from google console
please help me :)

**Comment by subhendukundu** [comment]
Can you add a bit of details of the errors if throwing any?

**Comment by arief-prasetyo** [comment]
i've created clientID from console.cloud.google.com and fill the clientID field with my clientID,,
the app running successfully but when i click login, choose the Gmail account and click allow nothing happen after this

![electrongoogle](https://user-images.githubusercontent.com/44457407/57996258-8e522a80-7af0-11e9-827c-82c36455a841.png)

sorry i use indonesian language on the app login

**Comment by subhendukundu** [comment]
You might want to take a look at https://developers.google.com/sheets/api/quickstart/nodejs
